name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
          php: [7.4, 7.3, 7.2, 7.1]
          dependency-version: [prefer-lowest, prefer-stable]
          os: [ubuntu-latest, windows-latest]

    name: P${{ matrix.php }} - ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Install composer dependencies
      run: composer install --prefer-dist
    - name: Run PHPUnit
      run: vendor/bin/phpunit